name: sync
on:
  push:
    branches:  tanishchoudhary-yoyo_1
jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    
    steps:
      - name: 'synccc'
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
          
          FILE_PATTERNS: |
            ^README\.md$
            ^build\.xml$
            ^pom\.xml$
            ^\jenkins\/Jenkinsfile$
           
          TARGET_REPOS: |
            tanishchoudhary/newone
            tanishchoudhary/My-Sctripts
