name: sync
on:
  push:
    branches:  tanishchoudhary-yoyo_1
jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    
    steps:
      - name: 'synccc'
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
          
          FILE_PATTERNS: |
            ^\.github\/workflows\/env\.yml$
            ^test\.json$
            ^README\.md$
            #^build\.xml$
            #^pom\.xml$
            #^\jenkins\/Jenkinsfile$
           # ^\src/\*$
           # ^\jenkins\/scripts\/deliver\.sh$
            
           
          TARGET_REPOS: |
            tanishchoudhary/newone@tanishchoudhary-yoyo_1
            tanishchoudhary/My-Sctripts@tanishchoudhary-yoyo_1
