name: sync
on:
  push:
    branches:  tanishchoudhary-yoyo_1
jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    
    steps:
    
      - run: |-
            git init
            
      - name: 'synccc'
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
          source_branch: tanishchoudhary-yoyo_1
          target_branch: master
          title: My pull request
#           template: .github/PULL_REQUEST_TEMPLATE.md
          body: "**Automated pull request**"
          reviewer: tanishchoudhary
#           assignee: octocat
#         label: enhancement
#         milestone: My milestone
          draft: true
#           old_string: "<!-- Add your description here -->"
#         new_string: "** Automatic pull request**"
          get_diff: true
#         ignore_users: "dependabot"
         
            
