
env:
  STACK: java
  BUILD_TECH: java_maven
  MVN_ARGS: clean install --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: false
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

on: 
  push:
    branches:
      - tanishchoudhary-yoyo_1
    
jobs:
  build:
    name: First job
    runs-on: ubuntu-latest
    
    steps:
      - name: 'checkout code"
        uses: action/checkout@v2.3.4
        
