
env:
  STACK: java
  BUILD_TECH: java_maven
  MVN_ARGS: clean install --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: false
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

on: 
  push:
    branches: [ tanishchoudhary-yo12 ]
    
jobs:
  build:
    name: First job
    runs-on: ubuntu-latest
    
    steps:
      - name: 'checkout coode'
        uses: actions/checkout@v2.4.0
        
