env:
  STACK: java
  BUILD_TECH: java_maven
  MVN_ARGS: clean install --batch-mode --update-snapshots verify
  CONTINUE_ON_ERROR: FALSE
  CONTINUE_ON_ERROR_SETUP: true
  JOB_STATUS_CODE: 0

on: 
  push:
    branches:  tanishchoudhary-yoyo_1 
    
jobs:
  build:
    name: First job
    runs-on: ubuntu-latest
    
    steps:
      - name: 'checkout coode ${{ github.REF }}'
        uses: actions/checkout@v2.4.0
        
      - name: 'directory'
        run: |
            pwd 
            ls
      - name: set up JDK 11
        id: setup_jdk
        uses: actions/setup-java@v2.4.0
        continue-on-error: TRUE
        #with:
        #  java-version: '11'
         # distribution: 'adot'
